Basic Authentication
mohammedabualsoud/sofather-hub pull request #18
Opened 2024-09-09 20:31 UTC by zainab1AT

This pull request includes the initial setup of the Express server, MySQL database connection, Data Access Layer (DAL), and basic user authentication functionalities.
The main features implemented are user registration (/signup) and login (/login) endpoints with password hashing and verification using bcrypt.

2024-09-17 20:14 UTC, mohammedabualsoud commented on projects/authentication_management/zainab1AT/authMiddleware.js
> +      req.auth = { username, password };
why you don't verify the user in this middleware instead ?

2024-09-17 20:19 UTC, mohammedabualsoud commented on projects/authentication_management/zainab1AT/authRoutes.js
> +  const hashedPassword = await bcrypt.hash(password, 12);
the controller shouldn't contains B.L, B.L should goes into services and Controller should be manager or managers/orchestrates the work.

Please refer to this article for more details:
https://www.coreycleary.me/what-is-the-difference-between-controllers-and-services-in-node-rest-apis

2024-09-17 20:20 UTC, mohammedabualsoud commented on projects/authentication_management/zainab1AT/authRoutes.js
> +router.post("/login",basicAuth, async (req, res) => {
no need for logic route better to move this to the basicAuth middleware

2024-09-17 20:21 UTC, mohammedabualsoud commented on projects/authentication_management/zainab1AT/userRoutes.js
> +async function isPasswordValid(pass, hashPass) {
as you can see you are duplicating this verification logic at every protected route. this should be act as middlewares as best practices.

2024-09-17 20:21 UTC, mohammedabualsoud commented on projects/budget_managment/zainab1AT/BudgetManagementService.js
> +  // error: when I add user already exist it print "added successfully " in App.js
remove not needed

2024-09-17 20:22 UTC, mohammedabualsoud commented on projects/budget_managment/zainab1AT/User.js
> +  #userName;
I think it's not relevant for this pull request

2024-09-17 20:22 UTC, mohammedabualsoud requested changes
Please look at my comments

2024-09-20 14:05 UTC, mohammedabualsoud commented on projects/authentication_management/zainab1AT/authMiddleware.js
> +      req.auth = { username, password };
@zainab1AT You better do the verification here, and inject the logged in user with the req object

2024-10-12 11:46 UTC, mohammedabualsoud commented on projects/authentication_management/zainab1AT/Server.js
> +app.use("/api/auth", userController);
I think this should be authController and the one below userController

2024-10-12 11:50 UTC, mohammedabualsoud commented on projects/authentication_management/zainab1AT/authMiddleware.js
> +        req.auth = { username, password};
you better apply the verification here, instead of keep doing it on ever API call/endpoint

2024-10-15 12:50 UTC, zainab1AT commented on projects/authentication_management/zainab1AT/authMiddleware.js
> +        req.auth = { username, password};
I did it.

2024-10-16 20:55 UTC, mohammedabualsoud commented on projects/authentication_management/zainab1AT/middlewares/authMiddleware.js
> +    if (req.method === 'POST' && req.path === '/login') {
you should do the verification on all routes. and no need for line 25

2024-10-16 20:55 UTC, mohammedabualsoud commented on projects/authentication_management/zainab1AT/routes/authRoutes.js
> +router.post("/signup", basicAuth, signup);
in order to signup this should be public route and not protected

2024-10-24 14:57 UTC, zainab1AT commented on projects/authentication_management/zainab1AT/routes/authRoutes.js
> +router.post("/signup", basicAuth, signup);
Could you please merge my pull request if everything looks good? I’m eager to finalize the complete JWT implementation. Thank you!

2024-11-09 18:43 UTC, mohammedabualsoud approved these changes

2024-11-09 18:43 UTC, merged