budget_managment/zainab1AT
mohammedabualsoud/sofather-hub pull request #2
Opened 2024-08-10 07:42 UTC by zainab1AT

2024-08-10 07:42 UTC, zainab1AT commented
budget_managment/zainab1AT

2024-08-10 07:45 UTC, zainab1AT commented
.

2024-08-10 12:31 UTC, mohammedabualsoud commented
@zainab1AT Please look at the contribution guide, description and title of the pull request

2024-08-10 12:33 UTC, mohammedabualsoud commented on node_modules/.package-lock.json
> +{
Remove all the not needed files.  including **node_modules**

2024-08-10 12:36 UTC, mohammedabualsoud commented on projects/budget_managment/zainab1AT/User.js
> +  #userName;
what are these ?

2024-08-10 12:38 UTC, mohammedabualsoud commented on projects/budget_managment/zainab1AT/User.js
> +  static users = new Map();
How come a class of User contains list of Users ?
this is not a User it's something we Call it UserCollection or UserStore.

2024-08-10 12:41 UTC, mohammedabualsoud commented on projects/budget_managment/zainab1AT/User.js
> +      return JSON.stringify({
Why you are returning JSON string ?

2024-08-10 12:42 UTC, mohammedabualsoud commented on projects/budget_managment/zainab1AT/User.js
> +        username: User.users.get(userName).getUsername(),
everyTime you all calling get user. 
You could do it once and use that user instance for getting all the details

2024-08-10 12:46 UTC, mohammedabualsoud commented on projects/budget_managment/zainab1AT/User.js
> +    if (typeof receiverUsername === "string" && typeof amount === "number") {
there are nested if else statements here. You could make it more readable.

2024-08-10 12:49 UTC, mohammedabualsoud commented on projects/budget_managment/zainab1AT/App.js
> +            new User(username, fname, lname);
if the user already exists, your output is not correct. the user added User added successfully will be printed for the user.

2024-08-10 12:58 UTC, mohammedabualsoud commented on projects/budget_managment/zainab1AT/User.js
> +  deposit(amount) {
following the Single Responsibility Principle, the User class is doing more than one job.
This is not something for the user, I think better to split the non-user class responsibility to another class maybe the Bank / BudgetManagerService/BudgetService that expose the deposit & transfer capabilities APIs

2024-08-10 13:01 UTC, mohammedabualsoud requested changes
Please check my comments, and add unit tests too.

2024-08-11 08:54 UTC, zainab1AT commented on projects/budget_managment/zainab1AT/User.js
> +  #userName;
I use # to make the fields private, ensuring they can't be accessed or modified directly from outside the class, protecting the internal state of my object. Especially since they are matters related to money, it's very private.

2024-08-11 08:57 UTC, zainab1AT commented on projects/budget_managment/zainab1AT/User.js
> +  static users = new Map();
Does that mean I have to create another class and put it in?

2024-08-11 09:12 UTC, zainab1AT commented on projects/budget_managment/zainab1AT/User.js
> +      return JSON.stringify({
When I see the form of the example that you put it in the readme file for this idea , It occurred to me that it is JSON.

2024-08-11 09:18 UTC, zainab1AT commented on projects/budget_managment/zainab1AT/App.js
> +            new User(username, fname, lname);
Okay, I corrected it.

2024-08-11 18:37 UTC, mohammedabualsoud commented on .gitignore
Please make sure to follow the **contribution guidelines**, all the files should be created within your **app** directory

2024-08-11 18:44 UTC, mohammedabualsoud commented on projects/budget_managment/zainab1AT/README.md
> +```npm install readline-sync```
clearly the library here is dependecny of the app. So this should be part of the package.json or whatever tool you used to manage the dependencies.
in your case the user should run this command to install the dependencies

`npm install`

2024-08-11 18:50 UTC, mohammedabualsoud commented on projects/budget_managment/zainab1AT/User.js
> +  #userName;
Please read the airbnb javascript best practices guide.

https://github.com/airbnb/javascript?tab=readme-ov-file#naming--leading-underscore

2024-08-11 18:53 UTC, mohammedabualsoud commented on projects/budget_managment/zainab1AT/User.js
> +    if (BudgetManagementService.users.has(userName)) {
well you have made the User & BudgetManagementService very coupled.
I think better to make the User class a simple data class representing the User, and the Budget one could be responsible to maintain the users. I saw that part are coupled between the two classes

2024-08-11 18:54 UTC, mohammedabualsoud commented on projects/budget_managment/zainab1AT/tempCodeRunnerFile.js
I think not needed. Please remove

2024-08-12 06:47 UTC, mohammedabualsoud commented
@zainab1AT Your Pull Request missing the unit tests & the description is empty. Could you please fill these 2 requirements

2024-08-13 09:10 UTC, mohammedabualsoud commented on projects/budget_managment/zainab1AT/User.js
> +  #userName;
@zainab1AT Can you apply the coding style I asked for please

2024-08-13 09:17 UTC, mohammedabualsoud commented on projects/budget_managment/zainab1AT/User.js
> +      return JSON.stringify({
Better to not convert it to JSON string

2024-08-14 21:11 UTC, mohammedabualsoud commented on projects/budget_managment/zainab1AT/BudgetManagementService.js
> +    else throw new Error("This User not found !");
no need for else block

2024-08-14 21:13 UTC, merged